version: '2.2'

services:

   mongo:
      image: mongo:4.0.4
      restart: always
      container_name: mongo-basic
      environment:
         - MONGODB_USER="user"
         - MONGODB_PASS="pass"
      volumes:
         - ./mongo_data:/data/db
         - ./mongo_data/log:/var/log/mongodb/
      ports:
         - "27017:27017"

   
   mongo-express:
      image: mongo-express:1.0.2
      container_name: mongoEX
      restart: always
      ports:
         - "8081:8081"
      environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=user
         - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
         - ME_CONFIG_MONGODB_URL=mongodb://mongo-basic:27017/

